In [1]:
## Finds posterior distribution of observed values assuming that k follows a binomial distribution. p is discrete in this case.

numerator <- function(k, n, posprobs, probsofprobs){
  ## finds the numerator -- ie P(k|p)P(p)
  ## k (integer) : the total number of observed successes.
  ## n (integer) : the total number of observed trials.
  ## posprobs (vector): possible p values associated with the random variable k.
  ## probsofprobs (vector): this is our prior, mapping a probability to each possible probability

  function(p){
    ## For a particular p, this will find the posterior probability of p given observed values. This is a function generator -- given
    ## values of k and n, we can then find the probability of any particular p.
    x <- posprobs[p]
    px <- probsofprobs[p]

    res <- (x^k)*((1 - x)^(n-k))*px
    return(res)
  }
}

denominator <- function(k,n, posprobs, probsofprobs){
  ## Finds the denominator, the multiplicative constant. Same for all values of p. P(k)
  sum(sapply(X = 1:length(posprobs),FUN= numerator(k,n, posprobs, probsofprobs)))
}

probabilityfinder <- function(k,n,p, posprobs, probsofprobs){
  ## Finds the posterior probability of a particular p value.
  numerator(k,n, posprobs, probsofprobs)(p)/denominator(k,n, posprobs, probsofprobs)
}

posterior <- function(k,n, posprobs, probsofprobs){
  ## Finds the posterior probability mass function of the p values.
  sapply(X = 1:length(posprobs),FUN=function(p) probabilityfinder(k,n,p, posprobs, probsofprobs))
}

log_transf_numerator <- function(k,n){
  ## finds the numerator -- ie P(k|p)P(p), using log transform to avoid machine zeros
  ## k (integer) : the total number of observed successes.
  ## n (integer) : the total number of observed trials.
  ## posprobs (vector): possible p values associated with the random variable k.
  ## probsofprobs (vector): this is our prior, mapping a probability to each possible probability
  function(p){
    ## For a particular p, this will find the posterior probability of p given observed values. This is a function generator -- given
    ## values of k and n, we can then find the probability of any particular p.

    x <- posprobs[p]
    px <- probsofprobs[p]

    mx <- max(sapply(posprobs, function(pr) k*log(pr) + (n - k)*log(1 - pr)))

    res <- exp(k*log(x) + (n - k)*log(1 - x) - mx) * probsofprobs[p]
    return(res)
  }
}

log_transf_denominator <- function(k,n){
  ## Finds the denominator, the multiplicative constant, using log transform for machine zeros. Same for all values of p. P(k)

  sum(sapply(X = 1:length(posprobs),FUN= log_transf_numerator(k,n)))
}

log_transf_probabilitydist <- function(k,n,p){
  ## Finds the posterior probability of a particular p value using log transform.
  log_transf_numerator(k,n)(p)/log_transf_denominator(k,n)
}

log_transf_posterior <- function(k,n){
  ## Finds the posterior probability mass function of the p values using log transform

  sapply(X = 1:length(posprobs),FUN=function(x) log_transf_probabilitydist(k,n,x))
}



# Example -- Thunderstorms
Example: consider if we observed 11 events -- as an example, the number of thunderstorms in a month. We want to estimate the probability of a thunderstorm
given the new data. Assuming weather each day is independent (which is a simplifying assumption), we can assume that the number of thunderstorms in n days can be modeled by
a binomial distribution. If we believe prior to this that the distribution looks as it does below (with the highest belief in 35 and 45%), we can now find the
posterior of the probabilities after observing the 11 thunderstorms as follows:


In [2]:
posprobs <- c(.05,.15,.25,.35,.45,.55,.65,.75,.85,.95)
probsofprobs <- c(.07,.13,.26,.26,.13,.07,.02,.02,.02,.02)
length(posprobs) == length(probsofprobs)

pos <- posterior(11,27,posprobs, probsofprobs)
pos

[1] TRUE

[1] 3.095425e-08 1.718005e-03 1.278404e-01 5.244571e-01 2.873813e-01
 [6] 5.673647e-02 1.826165e-03 4.046863e-05 4.523481e-08 3.571776e-15

So we now believe with `r round(pos[which.max(pos)],2)`  probability that the actual p value is `r posprobs[which.max(pos)]`. This means the data supports the assumption of `r posprobs[which.max(pos)]` chance of thunderstorms a day, given our prior beliefs and the independence of events.

# Behaviors for different n and k.



In [3]:
n <- c(10,50,100,150,200,300,500)
k <- lapply(n, function(n) seq(n/10,n,n/10))
lapply(1:7,function(i) sapply(1:10, function(j) posterior(k[[i]][j],n[i], posprobs, probsofprobs)))

[[1]]
              [,1]         [,2]         [,3]         [,4]         [,5]
 [1,] 1.599929e-01 3.044837e-02 4.175353e-03 4.535141e-04 3.970198e-05
 [2,] 3.275858e-01 2.090328e-01 9.611020e-02 3.500202e-02 1.027402e-02
 [3,] 3.539850e-01 4.266587e-01 3.705460e-01 2.549013e-01 1.413272e-01
 [4,] 1.367042e-01 2.661665e-01 3.734142e-01 4.149510e-01 3.716434e-01
 [5,] 1.954070e-02 5.781053e-02 1.232366e-01 2.080849e-01 2.831819e-01
 [6,] 2.112971e-03 9.338145e-03 2.973675e-02 7.500583e-02 1.524825e-01
 [7,] 7.431490e-05 4.990432e-04 2.414717e-03 9.254710e-03 2.858795e-02
 [8,] 4.150223e-06 4.502043e-05 3.518955e-04 2.178644e-03 1.087132e-02
 [9,] 4.740131e-08 9.712589e-07 1.433988e-05 1.676966e-04 1.580618e-03
[10,] 2.691558e-12 1.849159e-10 9.153996e-09 3.589348e-07 1.134342e-05
              [,6]         [,7]         [,8]         [,9]        [,10]
 [1,] 0.0000027423 1.387873e-07 4.323270e-09 6.308829e-11 3.898065e-13
 [2,] 0.0023794092 4.037659e-04 4.217143e-05 2.063387e-06 4.274713e-08
 [3,] 0.0618245522 1.981654e-02 3.909516e-03 3.613198e-04 1.413919e-05
 [4,] 0.2626259078 1.359817e-01 4.333627e-02 6.469879e-03 4.089826e-04
 [5,] 0.3040687011 2.392268e-01 1.158446e-01 2.627942e-02 2.524175e-03
 [6,] 0.2445832762 2.874519e-01 2.079370e-01 7.046474e-02 1.011058e-02
 [7,] 0.0696762613 1.244281e-01 1.367666e-01 7.042313e-02 1.535375e-02
 [8,] 0.0428016131 1.234723e-01 2.192337e-01 1.823553e-01 6.422345e-02
 [9,] 0.0117546882 6.405116e-02 2.148182e-01 3.375116e-01 2.245279e-01
[10,] 0.0002828487 5.167684e-03 5.811202e-02 3.061326e-01 6.828370e-01

[[2]]
              [,1]         [,2]         [,3]         [,4]         [,5]
 [1,] 2.322306e-01 2.277038e-04 1.627936e-08 1.818866e-13 3.574528e-19
 [2,] 7.025229e-01 2.919046e-01 8.843776e-03 4.187267e-05 3.487212e-08
 [3,] 6.469033e-02 6.463265e-01 4.708481e-01 5.360506e-02 1.073459e-03
 [4,] 5.556787e-04 6.106833e-02 4.893556e-01 6.128149e-01 1.349860e-01
 [5,] 5.305619e-07 4.722849e-04 3.065408e-02 3.109343e-01 5.547583e-01
 [6,] 9.330045e-11 6.178079e-07 2.982905e-04 2.250721e-02 2.987160e-01
 [7,] 7.534734e-16 4.041228e-11 1.580429e-07 9.659015e-05 1.038354e-02
 [8,] 4.093039e-22 2.414743e-16 1.038753e-11 6.983126e-08 8.257379e-05
 [9,] 7.955005e-32 1.128490e-24 1.167269e-18 1.886864e-13 5.364942e-09
[10,] 4.695776e-53 2.822892e-43 1.237364e-34 8.476110e-27 1.021294e-19
              [,6]         [,7]         [,8]         [,9]        [,10]
 [1,] 1.133380e-25 4.692851e-33 9.915429e-42 9.158596e-52 4.024562e-64
 [2,] 4.685598e-12 8.221589e-17 7.361397e-23 2.881425e-30 5.365704e-40
 [3,] 3.468201e-06 1.463279e-09 3.150385e-14 2.965123e-20 1.327682e-28
 [4,] 4.797193e-03 2.226331e-05 5.272371e-09 5.458393e-14 2.688413e-21
 [5,] 1.596901e-01 6.002831e-03 1.151458e-05 9.655674e-10 3.852028e-16
 [6,] 6.396382e-01 1.788605e-01 2.552161e-03 1.592005e-06 4.724468e-12
 [7,] 1.800931e-01 4.078990e-01 4.714352e-02 2.381957e-04 5.725563e-09
 [8,] 1.575337e-02 3.924721e-01 4.989510e-01 2.772998e-02 7.331850e-06
 [9,] 2.461095e-05 1.474333e-02 4.506889e-01 6.022830e-01 3.829100e-03
[10,] 1.985380e-13 5.040118e-08 6.529073e-04 3.697472e-01 9.961636e-01

[[3]]
               [,1]         [,2]         [,3]         [,4]         [,5]
 [1,]  1.681094e-01 3.253710e-07 2.125097e-15 2.142022e-25 4.909985e-37
 [2,]  8.283783e-01 2.879221e-01 3.377024e-04 6.112778e-09 2.516253e-15
 [3,]  3.512017e-03 7.057761e-01 4.786194e-01 5.009090e-03 1.192171e-06
 [4,]  2.591346e-07 6.300791e-03 5.169849e-01 6.546450e-01 1.885146e-02
 [5,]  4.724763e-13 7.537045e-07 4.057283e-03 3.370657e-01 6.368031e-01
 [6,]  2.713443e-20 2.395219e-12 7.134818e-07 3.279939e-03 3.428940e-01
 [7,]  6.193798e-30 3.587014e-20 7.010065e-13 2.114250e-07 1.450113e-03
 [8,]  1.827734e-42 1.280703e-30 3.028285e-21 1.105072e-13 9.170548e-08
 [9,]  6.904020e-62 2.797059e-47 3.823967e-35 8.068112e-25 3.871158e-16
[10,] 2.405669e-104 1.750229e-84 4.297013e-67 1.628110e-51 1.402853e-37
              [,6]         [,7]         [,8]          [,9]      

Each list represents n = 10,50,100,150,200,300,500, and each column represents possible ks from n/10 to n.
We see what is expected with Bayesian probabilities -- as n increases, our confidence in probabilities becomes stronger -- we get values that are nearly 1 for the observations
which have p = k/n and 0 otherwise. This shows that the prior does not matter in these cases, as we get more observations, the data will overwhelm the prior.
For small values of n, we see the opposite -- it is highly skewed by our prior, so that we are not so confident that p = k/n if p was not deemed probable prior.

# Machine Zeros problem:


In [4]:
posterior(1000,2000, posprobs, probsofprobs)

[1] NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN

Notice that we have many machine zeros for large n. This interferes with our calculations, and gives us NaNs for the calculations.
The following uses a log transformation to avoid machine zeros:



In [5]:
posterior(1000,2000, posprobs, probsofprobs)
log_transf_posterior(1000,2000)

[1] NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN

[1]  0.000000e+00 5.596221e-289 3.467465e-121  3.312387e-37  6.500000e-01
 [6]  3.500000e-01  2.547990e-38 2.667281e-122 8.609571e-290  0.000000e+00